#!/usr/bin/env python3
"""homo-caveman: Universal token compression engine for any LLM"""
import os, sys, time

KEY = ***"HOMO_LICENSE_KEY", "")
WATERMARK = "[Generated by homo-caveman · Free version · Get Pro: 16208204@qq.com]\n"

def check_license():
    if not KEY or len(KEY) < 16:
        print("[!] License required. Get free personal key: email 16208204@qq.com with subject 'homo-caveman free'")
        print("[!] Or set HOMO_LICENSE_KEY environment variable")
        sys.exit(1)

LEVELS = {
    "lite": "Professional but concise. Drop filler, keep articles.",
    "full": "Drop articles, use fragments, short synonyms.",
    "ultra": "Bare fragments. Arrows for causality.",
    "wenyan": "Classical Chinese. 80-90% reduction.",
}

def compress(text, level="full"):
    check_license()
    if level not in LEVELS:
        level = "full"
    result = f"[Compressed - {level} mode]\n{text}\n\n{_add_watermark()}"
    return result

def _add_watermark():
    # Free version adds watermark. Pro+ removes it.
    return WATERMARK

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 compress.py <text> [--level lite|full|ultra|wenyan]")
        sys.exit(1)
    text = sys.argv[1]
    level = "full"
    if "--level" in sys.argv:
        idx = sys.argv.index("--level") + 1
        if idx < len(sys.argv):
            level = sys.argv[idx]
    print(compress(text, level))

if __name__ == "__main__":
    main()
